Update for the latest nightly Rust
Tested with: `rustc 1.34.0-nightly (8ae730a44 2019-02-04)`

This commit fixes the compilation error: "can't perform LTO when
compiling incrementally" by disabling incremental compilation for the
`release` and `bench` profiles.

<https://github.com/rust-lang/cargo/pull/6564> enabled incremental
compilation by default but it cannot be used at the same time with
ThinLTO (hence the compile error). While incremental compilation
provides a significant boost to compilation speed, I consider that the
runtime performance is the utmost importance for these build types.